config/routes.rb
Parijs::Application.routes.draw do

  resources :voorstels

  get "home/index"
  
  devise_for :users

  root :to => "home#index"

  devise_for :users
  devise_scope :user do
      get 'register', to: 'devise/registrations#new', as: :register
      get 'logout', to: 'devise/sessions#destroy', as: :logout
      get 'login', to: 'devise/sessions#new', as: :login
  end

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  # attr_accessible :title, :body
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true,
                           format:  {
                             with: /^[a-zA-Z0-9_-]+$/
                           }

  def full_name
  	first_name + " " + last_name
  end
end

app/models/voorstel.rb
class Voorstel < ActiveRecord::Base
  attr_accessible :content, :name, :place, :time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/voorstels_controller.rb
class VoorstelsController < ApplicationController
  # GET /voorstels
  # GET /voorstels.json
  def index
    @voorstels = Voorstel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voorstels }
    end
  end

  # GET /voorstels/1
  # GET /voorstels/1.json
  def show
    @voorstel = Voorstel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voorstel }
    end
  end

  # GET /voorstels/new
  # GET /voorstels/new.json
  def new
    @voorstel = Voorstel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voorstel }
    end
  end

  # GET /voorstels/1/edit
  def edit
    @voorstel = Voorstel.find(params[:id])
  end

  # POST /voorstels
  # POST /voorstels.json
  def create
    @voorstel = Voorstel.new(params[:voorstel])

    respond_to do |format|
      if @voorstel.save
        format.html { redirect_to @voorstel, notice: 'Voorstel was successfully created.' }
        format.json { render json: @voorstel, status: :created, location: @voorstel }
      else
        format.html { render action: "new" }
        format.json { render json: @voorstel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voorstels/1
  # PUT /voorstels/1.json
  def update
    @voorstel = Voorstel.find(params[:id])

    respond_to do |format|
      if @voorstel.update_attributes(params[:voorstel])
        format.html { redirect_to @voorstel, notice: 'Voorstel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voorstel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voorstels/1
  # DELETE /voorstels/1.json
  def destroy
    @voorstel = Voorstel.find(params[:id])
    @voorstel.destroy

    respond_to do |format|
      format.html { redirect_to voorstels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/voorstels_helper.rb
module VoorstelsHelper
end

app/views/home/index.html.erb
<div class="contenttext">
	<% if user_signed_in? %>

	<h2><br>Welkom op explorer!<br></h2>

	<% else %>
	
	<h2><br>Welkom op world explorer! Gelieve in te loggen om de site te bezichtigen<br></h2>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="nl">

<head>

<title>Paris</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!-- Google font -->
<link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>

<!-- Bootstrap -->
<script type="text/javascript" src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">

    $('.carousel').carousel('cycle'){
    interval: 2000
    })

</script>

</head>

<body>

	<div class="navbar navbar-fixed-top navbar-inverse">
	    <div id="nav" class="navbar-inner">
	    	<div class="container-fluid">
	    		<div class="row-fluid">
		    		<!-- <div class="span3"></div> -->
		    		<div class="span12 nav">
					    <%= link_to image_tag("/assets/logo.png"), home_index_path, :class => 'brand logo' %>
					    <ul class="nav">
							<% if user_signed_in? %>
						    	<li><%= link_to current_user.first_name, edit_user_registration_path %></li>
						    	<li><%= link_to "Log out", logout_path %></li>
					    	<% else %>
					    		<li><%= link_to "Register", register_path %></li>
					    		<li><%= link_to "Log in", login_path %></li>
					    	<% end %>					    
					    </ul>
					</div>
				</div>
		    </div>
	    </div>
    </div>

	<div class="container-fluid">

		<div id="header" class="row-fluid">
			<div class="span12">
			    <div id="myCarousel" class="carousel slide">
					<!-- Carousel items -->
					<div class="carousel-inner">
						<div class="active item"><%=image_tag "/assets/parijs.jpg"%></div>
						<div class="item"><%=image_tag "/assets/parijs2.jpg"%></div>
						<div class="item"><%=image_tag "/assets/parijs3.jpg"%></div>
				    </div>
				    <!-- Carousel nav -->
				    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
				    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
				    </div>
				</div>	
			</div>

			<div id="content" class="row-fluid">
				<div class="span3">
					<div class="form">

						<% if user_signed_in? %>
							<ul>
								<li class="name">Welkom, <%= current_user.full_name %></li>
								<li><%= link_to "Voorstellen", voorstels_path %></li>
								<li><%= link_to "Account instellingen", edit_user_registration_path %></li>
								<li><%= link_to "Logout", logout_path %></li>
							</ul>
						<% else %>
							<h2>Login</h2>
							<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

								<div><%= f.label :email %>
								<%= f.email_field :email %></div>

								<div><%= f.label :password %>
								<%= f.password_field :password %></div>

								<div><%= f.submit "Sign in", :class =>'btn btn-small btn-inverse' %></div>
								<% end %>

							<%= render "devise/shared/links" %>
						<% end %>
					</div>

					<!-- <div class="info">
						<p>
							Indien u vragen heeft in verband met de planning of het ontwerp kan u mij altijd bereiken op mijn nummer -- te vinden in uw GSM onder de naam lieveken / schatteken / mijn ventsjen -- of door het volgende e-mail adres: <a href="mailto:huts.axel@gmail.com">huts.axel@gmail.com</a> ^^
						</p>
						<p>
							Deze site is alleen maar getest in firefox, chrome en safari! :)
						</p>
					</div> -->
				</div> 
				<div class="span9">

				<%= yield %>

			</div>
		</div>
	</div>

	<!--<div id="footer">
		<div class="row-fluid container-fluid">
			<div class="span12">
				<p>dfgsdfgdsfg</p>
			</div>
		</div>
	</div>-->
</body>

</html>

app/views/voorstels/_form.html.erb
<%= form_for(@voorstel) do |f| %>
  <% if @voorstel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voorstel.errors.count, "error") %> prohibited this voorstel from being saved:</h2>

      <ul>
      <% @voorstel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Uw naam' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place, 'De plaats die u wilt voorstellen' %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :time, 'De tijdsspanne die u voorziet' %><br />
    <%= f.select :time, [['0:30'],
                        ['1:00'],
                        ['1:30'],
                        ['2:00'],
                        ['2:30'],
                        ['3:00'],
                        ['3:30'],
                        ['4:00'],
                        ['4:30'],
                        ['5:00']] %>
  </div>
  <div class="field">
    <%= f.label :content, 'Opmerkingen bij het voorstel' %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Stel voor", :class =>'btn btn-medium btn-inverse' %>
  </div>
<% end %>

app/views/voorstels/edit.html.erb
<h1>Editing voorstel</h1>

<%= render 'form' %>

<%= link_to 'Show', @voorstel %> |
<%= link_to 'Back', voorstels_path %>

app/views/voorstels/index.html.erb
<h1>Lijst van voorstellen</h1>
<% @voorstels.each do |voorstel| %>
<div class="voorstellen">
  
  <table>
    <tr>
      <th>Naam</th>
      <th>Plaats</th>
      <th>Tijdspan</th>
      <th>Opmerking</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <tr>
      <td><%= voorstel.name %></td>
      <td><%= voorstel.place %></td>
      <td><%= voorstel.time %></td>
      <td><%= voorstel.content %></td>
    </tr>
    <tr colspan="4">
      <td><%= link_to 'Toon', voorstel, :class => "linkvoorstellen" %>
          <%= link_to 'Wijzig', edit_voorstel_path(voorstel), :class => "linkvoorstellen" %>
          <%= link_to 'Delete', voorstel, method: :delete, data: { confirm: 'Are you sure?' }, :class => "linkvoorstellen" %>
      </td>
    </tr>
  </table>

</div>
<% end %>

<%= link_to 'Nieuw voorstel', new_voorstel_path, :class => "newvoorstel" %>

app/views/voorstels/new.html.erb
<h1>Nieuw voorstel</h1>

<%= render 'form' %>

<%= link_to 'Back', voorstels_path %>

app/views/voorstels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Naam:</b>
  <%= @voorstel.name %>
</p>

<p>
  <b>Plaats:</b>
  <%= @voorstel.place %>
</p>

<p>
  <b>Tijdspanne:</b>
  <%= @voorstel.time %>
</p>

<p>
  <b>Opmerking:</b>
  <%= @voorstel.content %>
</p>


<%= link_to 'Edit', edit_voorstel_path(@voorstel) %> |
<%= link_to 'Back', voorstels_path %>